apiVersion: v1
kind: Service
metadata:
  name: dispatcharr
  namespace: dispatcharr
spec:
  ports:
  - name: main
    port: 9191
  selector:
    app: dispatcharr
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: dispatcharr
spec:
  ports:
  - port: 6379
  selector:
    app: redis
