apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodecast
  namespace: nodecast
spec:
  selector:
    matchLabels:
      app: nodecast
  template:
    metadata:
      labels:
        app: nodecast
    spec:
      containers:
        - env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "3000"
          envFrom:
            - secretRef:
                name: nodecast-oidc
          image: ghcr.io/technomancer702/nodecast-tv:latest
          imagePullPolicy: Always
          name: nodecast
          ports:
            - containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /app/data
              name: nodecast-data
      volumes:
        - name: nodecast-data
          persistentVolumeClaim:
            claimName: nodecast-data
