apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nodecast
  namespace: nodecast
spec:
  defaultBackend:
    service:
      name: nodecast
      port:
        name: http
  ingressClassName: tailscale
  tls:
    - hosts:
        - nodecast
