apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bichon
  name: bichon
  namespace: bichon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bichon
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bichon
    spec:
      containers:
        - env:
            - name: BICHON_LOG_LEVEL
              value: info
            - name: BICHON_ROOT_DIR
              value: /data
            - name: BICHON_ENCRYPT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: bichon-encrypt-password
          image: rustmailer/bichon:latest
          name: bichon
          ports:
            - containerPort: 15630
              name: http
          resources:
            requests:
              cpu: 1000m
              memory: 1Gi
          volumeMounts:
            - mountPath: /data
              name: data
      securityContext:
        fsGroup: 100
        runAsGroup: 100
        runAsUser: 1000
      volumes:
        - name: data
          nfs:
            path: /r2d2_0/homes/mhelton/misc/gmail_export
            server: 100.117.238.67
