apiVersion: v1
kind: Service
metadata:
  labels:
    app: bichon
  name: bichon
  namespace: bichon
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 15630
  selector:
    app: bichon
  type: ClusterIP
