apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: bichon-secrets
  namespace: bichon
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3eHdlMHp3MW93c014QUV1
        UUxlTTUvelF5VlA4TC9FRlRYRWlFUkdZTUdJCmRheUZZZzNLZWs0NHZlbTNGcGU1
        YVFtcENZUEZDVTB3d2FpbllaWXorQm8KLS0tIE82c0hsZ0R4TDVVRnMvUSszQzk5
        a0tOUk5TdjRhRmtBQ0dCRnRIYVk2Sm8KSMBQIqYgoFkG1WQJGZ2/o3GnKY6g4QS0
        y0JYmlnQoECJn830jfTaZUT0NV6av5P2Gx6R7jEDnunPDQK79Xew+w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1m97ls72xcy8v492xrru4keyjve0jcqytqne6jk62zl72j3xsqgrql0ckw2
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIVjhzUkd5VVZxUXRyeFky
        NEM5NUJXYXJNQkRoSHJwMkw4aGk3MGtBZ0FrCmVYYi9vRndFN2R3ZkUrMzdJaWVm
        Wjd4dDd1eFdRMzdCZS83ajF5Y1JoV2sKLS0tIHIwNnpFbnhGRHJXN1hKT2lxOE9I
        czhtbFVJSDFRSzd5emRBc1dyY0k2eFkKUrKcQk2ObJqIem19q9DgtRcmXO6PLbSv
        7ixx9QqS2dqKVnd/o0QE2GvxmQXxujFwar/2HsTrH6ECpS1NU5Bp8A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qcn2u0r03z48ytvn9tts9pkllyj9qx7zl4w0yn6uscghv3f5y9jqmvyy69
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-01-31T17:19:30Z"
  mac: ENC[AES256_GCM,data:JAYL/fO+lIKGfiipmfyFuGhIQsp/7lSRABJSZyBJ3ZGQigzADpc/1rEuRYe+TgS18U8xMDkiFp2XV4DA50yKwcQ5KNhTx9zWkJjNO8efiaSWNZreKyjZ+lQYzZLNftWmUjyGGYDU5BkNyW3qqNFrL0v2ZKDS8i6mv15V5DGY/Xw=,iv:Lr56uZbqxJglaemIyXVZ/jHjfA54WTKHsCUb8jvDC9U=,tag:ipi4821iU/GL3t45xtTK0Q==,type:str]
  version: 3.11.0
spec:
  secretTemplates:
    - name: bichon-encrypt-password
      stringData:
        password: ENC[AES256_GCM,data:F9eIqcRUZppToq3cUCJysPULNYeegJe9,iv:/oaqhz/KqYLpuUe9xAk7aoM2CiIa9kprNRBG3gA1Wx0=,tag:Uey6RISA7FeyawXE5nK58g==,type:str]
  suspend: false
