apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dispatcharr
  namespace: argocd
spec:
  destination:
    namespace: dispatcharr
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./manifests/prod/dispatcharr
    repoURL: https://github.com/devusb/argocd.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
